### ISSUE TITLE
OS Language reporting for Windows Desktop apps

### ISSUE THREAD

**Issue by tomntech** [Countly/countly-sdk-windows#12]
iOS and Android SDK's provide functionality to report language, using device metrics. As is stands, Metrics in the Windows SDK does not collect Locale information.

```C#        
/// <summary>
/// Creates Metrics object with provided values
/// </summary>
/// <param name="OS">Name of the current operating system</param>
/// <param name="OSVersion">Current operating system version</param>
/// <param name="Device">Current device model</param>
/// <param name="Resolution">Device resolution</param>
/// <param name="Carrier">Cellular mobile operator</param>
/// <param name="AppVersion">Application version</param>
public Metrics(string OS, string OSVersion, string Device, string Resolution, string Carrier, string AppVersion)
{
    this.OS = OS;
    this.OSVersion = OSVersion;
    this.Device = Device;
    this.Resolution = Resolution;
    this.Carrier = Carrier;
    this.AppVersion = AppVersion;
}
```

Extending the SDK to incorporate this functionality would allow developers to understand in which languages their software should support. Culture info can be obtained via the following

```C#
Thread.CurrentThread.CurrentUICulture
```

**Comment by ArtursKadikis** [comment]
This is something I'll try to implement for the next release.

**Comment by tomntech** [comment]
@ArtursKadikis, do you have an ETA on when we can expect the next windows SDK release? There are a few features it would be great to see (Language reporting, GDPR acceptance, .NET 4.6.1 and 4.7 support, event duration).

**Comment by ArtursKadikis** [comment]
Hi, currently the ETA i'm targeting is 2-3 months.

**Comment by ArtursKadikis** [comment]
I'll try to do the most wanted ones and the easiest first

**Comment by ArtursKadikis** [comment]
Added locale reporting in 18.10.0
