### ISSUE TITLE
Inconsistent functionality across SDK's in regards to DeviceInfo

### ISSUE THREAD

**Issue by tomntech** [Countly/countly-sdk-windows#18]
The Windows SDK reports a PC name, rather than a device model as found in the Android SDK. A PC name is information we don't need and potentially breaks away from the anonymity provided by the rest of the API.

For Android, the following is executed
``` JAVA
static String getDevice() {
    return android.os.Build.MODEL;
}
```
Thus the model of the device is returned. 

However, when using the Windows SDK the following is executed
```C#
protected override string GetDeviceName()
{
    return System.Environment.MachineName;
}
```

**Comment by tomntech** [comment]
Is there a roadmap for upcoming countly-sdk-windows releases? Looking forward to seeing this issue resolved. My suggestion would be that we simply provide an empty string for model. The only other way to gather hardware information is through the WMI API which is notoriously slow.

**Comment by ArtursKadikis** [comment]
Hello, yes there is a internal roadmap for future releases. I'll add this to the list of additional improvements that are planned. The next version will probably arrive at the end of december.

**Comment by tomntech** [comment]
Hello, are there any updates on a Windows SDK release for this issue?

**Comment by ArtursKadikis** [comment]
Hello, due to other schedulling issues it was a little postponed. It should be released in the comming week.

**Comment by ArtursKadikis** [comment]
This should have been fixed in the current release.
