### ISSUE TITLE
Recording exceptions resulting in 414 URI Too Long

### ISSUE THREAD

**Issue by hrestakd** [Countly/countly-sdk-windows#19]
Good day,
we have been using your windows SDK and noticed that ocassionally nothing would be reported using the `CountlyBase.RecordException`.

Upon further investigation we found out that the request would fail with a 414 URI Too Long. The reason being that the stack trace is sent as a query string too.
[https://github.com/Countly/countly-sdk-windows/blob/f797f97bdbae61d7801f83a7b8269593b16e3e04/countlyCommon/countlyCommon/Server/ApiBase.cs#L67](https://github.com/Countly/countly-sdk-windows/blob/f797f97bdbae61d7801f83a7b8269593b16e3e04/countlyCommon/countlyCommon/Server/ApiBase.cs#L67)

Testing different request lengths I found out that ~8000 characters can still be sent, so I was wondering at what value have you defined your max request length? It would help us handle such exceptions better.

Also, is there any chance that this API method will be updated so the stack trace is sent inside the body of the request?

**Comment by ArtursKadikis** [comment]
Hello,

Yes, there seems to have been insufficient checks for such cases. In the next version I'll make sure that no url is longer then 2048 characters so that these kind of problems can be avoided.

**Comment by hrestakd** [comment]
Thanks for answering, although the problem of not being able to see a large stack trace in Countly would not be solved by this.

For example making a few nested Aggregate Exceptions and sending their stack traces would easily hit the mark of 2048 characters.

If you could preserve backward compatibility, wouldn't it be best if you were sending a POST request, with the stack trace inside the body?

That way the whole trace would always be sent.

**Comment by ArtursKadikis** [comment]
This should have been fixed in the current release.
