### ISSUE TITLE
Exception Recording

### ISSUE THREAD

**Issue by SwipeX** [Countly/countly-sdk-windows#20]
Calling `  await Countly.RecordException(message, stackTrace);` however, I do not get any crashes to show, and the DB is empty.

I am getting events for RecordEvent.

**Comment by SwipeX** [comment]
This seems like it is directly related to #19. If i limit my stack trace to under 300 characters, it submits fine, but longer stack traces result in the exceptions not making it to the server.

**Comment by SwipeX** [comment]
@ArtursKadikis I believe that sending the stackTrace in the body seems to have solved the issue for me. It may be advisable to update the SDK to do the same.

**Comment by ArtursKadikis** [comment]
Hello,
The SDK currently sends the stack trace (or any other request) in the body if the total request length is at least 2000 characters. Are you saying that for you it fails if it is longer than 300 characters? What project type are you using and which SDK are you using?

**Comment by SwipeX** [comment]
I am SDK version 19.02 of the Windows SDK (latest on Nuget). I am using C# in a 4.5 winforms application -- using the example code provided. In order for my exceptions to actually show up in my count.ly instance, I have to call the method like so: `Countly.RecordException(message, stackTrace.Substring(0, 255));`

**Comment by DaytonG** [comment]
Having the same issue. My exceptions rarely make it to my server. I believe this is related:

```
POST https://dev-countly.morphiclite-oregondesignservices.org/i
Encountered a exception while making a POST request, System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CountlySDK.Api.RequestAsync(String address, String requestData, Stream imageData) in D:\programming\Countly\countly-sdk-windows\pcl\Countly\Server\Api.cs:line 56
```

I am using the 20.05 SDK.

**Comment by ArtursKadikis** [comment]
Thank for reporting this. Will look into it.

**Comment by DaytonG** [comment]
If it helps, I captured a request that seems to trigger some of the logic.

`https://dev-countly.morphiclite-oregondesignservices.org/i?app_key=63938362cc85877174019abcc21b6f15f81b1d8d&device_id=C9FB2E7614C54C25BAB61EC15BFC593A&crash=%7B%22_os%22%3A%22Windows%2010%22%2C%22_os_version%22%3A%2210.0.18362.0%22%2C%22_app_version%22%3A%224.5.6%22%2C%22_online%22%3Atrue%2C%22_name%22%3A%22test%20exception%22%2C%22_error%22%3A%22%20%20%20at%20MorphicWin.QuickStrip.Zoom%28Object%20sender%2C%20ActionEventArgs%20e%29%20in%20C%3A%5C%5CUsers%5C%5Cxerxe%5C%5CRiderProjects%5C%5CMorphicLiteClientWindows%5C%5CMorphicWin%5C%5CQuickStrip.xaml.cs%3Aline%20315%5Cr%5Cn%20%20%20at%20MorphicWin.QuickStripSegmentedButtonControl.Button_Click%28Object%20sender%2C%20RoutedEventArgs%20e%29%20in%20C%3A%5C%5CUsers%5C%5Cxerxe%5C%5CRiderProjects%5C%5CMorphicLiteClientWindows%5C%5CMorphicWin%5C%5CQuickStripSegmentedButtonControl.xaml.cs%3Aline%20179%5Cr%5Cn%20%20%20at%20System.Windows.RoutedEventHandlerInfo.InvokeHandler%28Object%20target%2C%20RoutedEventArgs%20routedEventArgs%29%5Cr%5Cn%20%20%20at%20System.Windows.EventRoute.InvokeHandlersImpl%28Object%20source%2C%20RoutedEventArgs%20args%2C%20Boolean%20reRaised%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.RaiseEventImpl%28DependencyObject%20sender%2C%20RoutedEventArgs%20args%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.RaiseEvent%28RoutedEventArgs%20e%29%5Cr%5Cn%20%20%20at%20System.Windows.Controls.Primitives.ButtonBase.OnClick%28%29%5Cr%5Cn%20%20%20at%20System.Windows.Controls.Button.OnClick%28%29%5Cr%5Cn%20%20%20at%20System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp%28MouseButtonEventArgs%20e%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.OnMouseLeftButtonUpThunk%28Object%20sender%2C%20MouseButtonEventArgs%20e%29%5Cr%5Cn%20%20%20at%20System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler%28Delegate%20genericHandler%2C%20Object%20genericTarget%29%5Cr%5Cn%20%20%20at%20System.Windows.RoutedEventArgs.InvokeHandler%28Delegate%20handler%2C%20Object%20target%29%5Cr%5Cn%20%20%20at%20System.Windows.RoutedEventHandlerInfo.InvokeHandler%28Object%20target%2C%20RoutedEventArgs%20routedEventArgs%29%5Cr%5Cn%20%20%20at%20System.Windows.EventRoute.InvokeHandlersImpl%28Object%20source%2C%20RoutedEventArgs%20args%2C%20Boolean%20reRaised%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.ReRaiseEventAs%28DependencyObject%20sender%2C%20RoutedEventArgs%20args%2C%20RoutedEvent%20newEvent%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.OnMouseUpThunk%28Object%20sender%2C%20MouseButtonEventArgs%20e%29%5Cr%5Cn%20%20%20at%20System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler%28Delegate%20genericHandler%2C%20Object%20genericTarget%29%5Cr%5Cn%20%20%20at%20System.Windows.RoutedEventArgs.InvokeHandler%28Delegate%20handler%2C%20Object%20target%29%5Cr%5Cn%20%20%20at%20System.Windows.RoutedEventHandlerInfo.InvokeHandler%28Object%20target%2C%20RoutedEventArgs%20routedEventArgs%29%5Cr%5Cn%20%20%20at%20System.Windows.EventRoute.InvokeHandlersImpl%28Object%20source%2C%20RoutedEventArgs%20args%2C%20Boolean%20reRaised%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.RaiseEventImpl%28DependencyObject%20sender%2C%20RoutedEventArgs%20args%29%5Cr%5Cn%20%20%20at%20System.Windows.UIElement.RaiseTrustedEvent%28RoutedEventArgs%20args%29%5Cr%5Cn%20%20%20at%20System.Windows.Input.InputManager.ProcessStagingArea%28%29%5Cr%5Cn%20%20%20at%20System.Windows.Input.InputManager.ProcessInput%28InputEventArgs%20input%29%5Cr%5Cn%20%20%20at%20System.Windows.Input.InputProviderSite.ReportInput%28InputReport%20inputReport%29%5Cr%5Cn%20%20%20at%20System.Windows.Interop.HwndMouseInputProvider.ReportInput%28IntPtr%20hwnd%2C%20InputMode%20mode%2C%20Int32%20timestamp%2C%20RawMouseActions%20actions%2C%20Int32%20x%2C%20Int32%20y%2C%20Int32%20wheel%29%5Cr%5Cn%20%20%20at%20System.Windows.Interop.HwndMouseInputProvider.FilterMessage%28IntPtr%20hwnd%2C%20WindowMessage%20msg%2C%20IntPtr%20wParam%2C%20IntPtr%20lParam%2C%20Boolean%26%20handled%29%5Cr%5Cn%20%20%20at%20System.Windows.Interop.HwndSource.InputFilterMessage%28IntPtr%20hwnd%2C%20Int32%20msg%2C%20IntPtr%20wParam%2C%20IntPtr%20lParam%2C%20Boolean%26%20handled%29%5Cr%5Cn%20%20%20at%20MS.Win32.HwndWrapper.WndProc%28IntPtr%20hwnd%2C%20Int32%20msg%2C%20IntPtr%20wParam%2C%20IntPtr%20lParam%2C%20Boolean%26%20handled%29%5Cr%5Cn%20%20%20at%20MS.Win32.HwndSubclass.DispatcherCallbackOperation%28Object%20o%29%5Cr%5Cn%20%20%20at%20System.Windows.Threading.ExceptionWrapper.InternalRealCall%28Delegate%20callback%2C%20Object%20args%2C%20Int32%20numArgs%29%5Cr%5Cn%20%20%20at%20System.Windows.Threading.ExceptionWrapper.TryCatchWhen%28Object%20source%2C%20Delegate%20callback%2C%20Object%20args%2C%20Int32%20numArgs%2C%20Delegate%20catchHandler%29%22%2C%22_nonfatal%22%3Afalse%2C%22_logs%22%3A%22%22%2C%22_run%22%3A5%2C%22_custom%22%3A%7B%22booh%22%3A%22waah%22%7D%7D&sdk_version=20.05&sdk_name=csharp-netstd`

**Comment by ArtursKadikis** [comment]
Thanks, that really helps!

**Comment by DaytonG** [comment]
And lastly, if you want to reproduce it (pardon any of my code... I'm not a c# guy): https://github.com/oregondesignservices/MorphicLiteClientWindows/tree/feature/dgomez-send-exceptions

1. Clone that
2. build and run app
3. click the + or - buttons under "text size" a few times. Sometimes it fails, sometimes it does not.

Oh, and the server is 20.04 community.

**Comment by ArtursKadikis** [comment]
This should be fixed in the latest version
