### ISSUE TITLE
Exception Recording UWP version

### ISSUE THREAD

**Issue by WesleyKhoiVo** [Countly/countly-sdk-windows#21]
I have a issue exception recording with UWP version example. If I use WinForms 3.5 example, it work fine. but UWP version not show any exception (I copied WinForms RecordException function to UWP).
`try
            {
                throw new Exception("This is some bad exception 3");
            }
            catch (Exception ex)
            {
                Dictionary<string, string> customInfo = new Dictionary<string, string>();
                customInfo.Add("customData", "importantStuff");
                Countly.RecordException(ex.Message, ex.StackTrace, customInfo);
            }`
But I saw UWP log in sessions is recorded

**Comment by WesleyKhoiVo** [comment]
I am tested release ver 18.1.0 with WP8 project (on WP 8.1 and W10M), it can send exception. I think the problem could be PCL library, which is not available in WP8 project. 
And UWP project lastest version has pfx key should be removed

**Comment by ArtursKadikis** [comment]
Hello, I just released a version that removes PCL from the UWP version. Let me know if you still encounter this problem.
