### ISSUE TITLE
Consent features not being tracked correctly

### ISSUE THREAD

**Issue by tnoble-accelita** [Countly/countly-sdk-windows#22]
Windows SDK version: 19.8.0
Countly Server Community Edition: v18.08.2

When calling the following in the Windows SDK:
```csharp        
public void UpdateConsent(bool consent)
{
    Countly.Instance.SetConsent(new Dictionary<ConsentFeatures, bool>
    {
        { ConsentFeatures.Crashes, consent },
        { ConsentFeatures.Events, consent },
        { ConsentFeatures.Location, false },
        { ConsentFeatures.Sessions, consent },
        { ConsentFeatures.Users, false },
        { ConsentFeatures.Views, consent }
    });
}
```

The following output can be seen in the compliance hub in Countly Server:
![image](https://user-images.githubusercontent.com/53700997/78112333-fef6f280-73f5-11ea-91d3-be1dc638bc0b.png)

As a result, there is no tractability in the Metrics tab and all features are being tracked. 

API Server Log contains the following error:
```
Parse consent JSON failed {"crashes":true,"events":true,"location":false,"sessions":true,"users":false,} /i?app_key=redacted&device_id=fa60......&timestamp=1585728023144&consent=%7B%22crashes%22%3Atrue%2C%22events%22%3Atrue%2C%22location%22%3Afalse%2C%22sessions%22%3Atrue%2C%22users%22%3Afalse%2C%7D 
```

**Comment by ArtursKadikis** [comment]
Thanks for reporting this issue! This bug should be fixed in the just released 19.8.1 version.
