### ISSUE TITLE
Found Issue With SDK and Items in Queue

### ISSUE THREAD

**Issue by MackyBwoy22** [Countly/countly-sdk-windows#25]
In the UploadStoredRequests function of CountlyBase.cs there is an issue if the first session in the queue is a duplicate one. In this case, the if statement below does not process the request. Ideally, if it is a duplicate request it should be removed from the queue and continue processing the rest of the queue. To add a condition for duplicate requests to the if statement to allow the queue to continue processing.

 if (requestResult != null && (requestResult.IsSuccess() || requestResult.IsBadRequest()) || /* request is duplicate == true      */)

**Comment by ArtursKadikis** [comment]
Hello. How in your case did you create that "duplicate" request?

There is already a solution planned for issues similar to this.

**Comment by MackyBwoy22** [comment]
Not sure, I just realized that my events weren't going through so I took the countly_data folder and a copy of the SDK and debugged and found the issue above.

**Comment by ArtursKadikis** [comment]
Hello, this should already have been fixed
