### ISSUE TITLE
RecordEvent doesn't work

### ISSUE THREAD

**Issue by dbereghici** [Countly/countly-sdk-windows#26]
I created a small console app and I tried to record an event. The result is always false.
I used Telerik Fiddler to intercept the POST request and I noticed that the app_key query parameter value is always 'ZZ', instead of the app key set in CountlyConfig, resulting in a 400 Bad Request

Source code (I used the correct appkey & url)

`
    class Program
    {
        static async Task Main(string[] args)
        {

            await Countly.Instance.Init(new CountlyConfig()
            {
                serverUrl = "...",
                appKey = "...",
                appVersion = "...",
                deviceIdMethod = Countly.DeviceIdMethod.windowsGUID
            });

            await Countly.Instance.SessionBegin();

            var segmentation = new Segmentation();
            segmentation.Add("objectId", Guid.NewGuid().ToString());

            var result = await Countly.RecordEvent("SyncErrorPostDownload", 1, segmentation);

        }
    }
`

**Comment by ArtursKadikis** [comment]
I would assume that during a test run you used the appKey "ZZ". Then because a app with such a appKey does not exist on your server, the request got stuck.

**Comment by dbereghici** [comment]
@ArtursKadikis, that's strange. It doesn't work on 20.5.0 and 20.5.1, but if I downgrade to 19.8.1 it does work.

**Comment by ArtursKadikis** [comment]
I think that version dropped requests if a 400 error code was received. That logic was later reworked as it could lead to accidental deletion of data in case of server missconfiguration.

**Comment by dbereghici** [comment]
@ArtursKadikis  I wonder were is the request stuck and how I can make it work. I used different server url, but the app key is also 'ZZ'.

**Comment by ArtursKadikis** [comment]
Internally the SDK has a request queue which is executed in order. AppKey is one of the parameters attached to a request. Unless you clear the request queue the request will still have that app key.

It looks like the one request made with that appKey is holding up the other requests.

**Comment by dbereghici** [comment]
I see, now it makes sense :) One last question, how can I clear the request queue?

**Comment by ArtursKadikis** [comment]
It looks like currently there are no exposed calls for clearing the queue. You would have to find the file where the requests are stored and delete it. In the future we'll add calls to better interract with our request queue.

**Comment by dbereghici** [comment]
Great! Thank you for the support and quick responses ! :)
