### ISSUE TITLE
.NET 5 Version not updated

### ISSUE THREAD

**Issue by dbereghici** [Countly/countly-sdk-windows#27]
Hi. 
I created a .NET 5 app and I added the latest stable version of Countly (20.5.1) and I noticed it's not updated (different version from .NET Framework)
For e.g.: missing `GenerateDeviceIdMultipleFields` and `SetCustomDataPath` methods.

**Comment by ArtursKadikis** [comment]
Hello, yes we currently have not yet released a newer version of it. 

The reason for the missing fields is probably that nuget is picking a unexpected SDK flavor. We have 5 different builds of it with 3 major versions.

You probably previously used a .net3.5 project. That is the only flavor which saves the SDK data locally. The other flavors save it in isolated storage and therefore the custom data path is not relevant.

Currently also "GenerateDeviceIdMultipleFields" is also available only for our .net3.5 and .net4.0 flavors.
