### ISSUE TITLE
UWP on Windows 10

### ISSUE THREAD

**Issue by robertmackness** [Countly/countly-sdk-windows#7]
On Windows 10 desktop, using a UWP application that has the Count.ly Windows SDK, large amounts of temporary files are created and never cleared in the following folder:
C:\Users\User\AppData\Local\Packages\UwpApplicationUsingCountly\LocalState

Calling Countly.Halt() doesn't clear these, and new files are generated continuously until they fill the PC's entire hard drive.

This happens during all active sessions, despite calling the relevant StartSession and EndSession methods. Note - the UserDetails object is null during these tests.

![countlybug](https://user-images.githubusercontent.com/8677760/34617458-679d97c2-f233-11e7-95a4-23286ea833aa.PNG)

**Comment by robertmackness** [comment]
Some example file contents (we tried setting some UserDetails like username to see if the null userdetails was causing an problem, but this didn't work):
`<CountlyUserDetails xmlns="http://schemas.datacontract.org/2004/07/CountlySDK.Entities" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><BirthYear i:nil="true"/><Custom><items/></Custom><Email i:nil="true"/><Gender i:nil="true"/><Name i:nil="true"/><Organization i:nil="true"/><Phone i:nil="true"/><Picture i:nil="true"/><Username>testUser</Username><isChanged>false</isChanged></CountlyUserDetails>`

`<ArrayOfSessionEvent xmlns="http://schemas.datacontract.org/2004/07/CountlySDK.Entities" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/>`

`<ArrayOfSessionEvent xmlns="http://schemas.datacontract.org/2004/07/CountlySDK.Entities" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><SessionEvent i:type="BeginSession"><Content>/i?app_key=removedForSecurity123&amp;device_id=removedForSecurity123&amp;sdk_version=1.0&amp;begin_session=1&amp;metrics=%7B%22_os%22%3A%22WINDOWS%22%2C%22_device%22%3A%22+%22%2C%22_resolution%22%3A%221080x1920%22%2C%22_carrier%22%3A%22%22%2C%22_app_version%22%3A%222.9.3.0%22%7D&amp;timestamp=1515170386</Content></SessionEvent></ArrayOfSessionEvent>`

**Comment by robertmackness** [comment]
I can see that our server is logging events sent by our UWP app, so it doesn't seem that the SDK is caching these files due to connectivity problems.

**Comment by ArtursKadikis** [comment]
Thank you for your reporting, I'm currently trying to find the problem.

**Comment by ArtursKadikis** [comment]
@robertmackness which of our windows targets were you using? .net35, .net4, pcl, windows?

**Comment by robertmackness** [comment]
@ArtursKadikis 
We're using Microsoft.NETCore.UniversalWindowsPlatform 5.1.0, with Countly 1.2.9

**Comment by ArtursKadikis** [comment]
Hello, a small update to this issue. In short, it seems that nuget is giving you binaries that are meant for windows phone 8. Updating nuget to include a version specifically for UWP should fix the problem.

**Comment by ArtursKadikis** [comment]
Hello, we just released a new version of the sdk. Could you please check if the problem is fixed?
