### ISSUE TITLE
Allow DeviceData to be set

### ISSUE THREAD

**Issue by ptsteele** [Countly/countly-sdk-windows#95]
For our application we're looking to manually control the device information that is recorded for a session. It appears that all the fields we'd like to change exist but are locked behind internal classes.

https://github.com/Countly/countly-sdk-windows/blob/master/countlyCommon/countlyCommon/CountlyBase.cs#L141 

Is there any chance there could be an option to set the values in `Device.cs` through a configuration, or at a minimum remove the internal tag from these fields / classes so they could be extended and overwritten by consuming applications?

I'd be happy to whip up a PR if that is an acceptable idea but there is not bandwidth for it.

**Comment by ZahidZafar** [comment]
Hello @ptsteele ,

It sounds like you are referencing the fields that are sent under the "metric" parameter when sending together a request that sends the "begin_session" parameter. The ability to override these values is something that we want to add, and it currently already was on our roadmap.

Thank you for offering to create a PR for this, but we'll be implementing and releasing this ourselves in the next 1-2 months.
